spring.application.name=nuevo-avatar-persona4-test
spring.datasource.url=jdbc:h2:mem:expedientes;MODE=MSSQLServer;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/esquema-h2-v3.sql
seguridad.service.url=http://seguridad.test
seguridad.connect-timeout-ms=3000
seguridad.read-timeout-ms=5000
direccion.service.url=http://direccion.test
matricula.service.url=http://matricula.test
