spring.application.name=nuevo-avatar-persona4
server.port=${SERVER_PORT:8084}
seguridad.service.url=${SEGURIDAD_BASE_URL:http://localhost:5158}
seguridad.connect-timeout-ms=${SEGURIDAD_CONNECT_TIMEOUT_MS:3000}
seguridad.read-timeout-ms=${SEGURIDAD_READ_TIMEOUT_MS:5000}
direccion.service.url=${DIRECCION_BASE_URL:http://localhost:5227}
matricula.service.url=${MATRICULA_BASE_URL:http://localhost:8085}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.sql.init.mode=never
